version: '3'

networks:
  appt:
  
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes: 
      - ../src:/var/www
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks:
      - appt

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes: 
      - ../mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: appointments
      MYSQL_USER: appointments
      MYSQL_PASSWORD: 34udXjhTSQ7BvjcE
      MYSQL_ROOT_PASSWORD: 5ssaZbs5EFatrHQS54VAuuycmfrsRPCU
      SERVICE_NAME: mysql
    networks:
      - appt

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes: 
      - ../src:/var/www
    networks:
      - appt
